### ISSUE TITLE
Make the Danish BERT better (allow MISC)

### ISSUE THREAD

**Issue by sorenmulli** [peleiden/daluke#10]
BERT is probably the SoTA on DaNE, as per the DaNE paper, but this becomes muddy, when the danlp version cannot predict MISC + has lower performance than the DaNE paper.

As the Alexandre Institute cannot explain this (the authors are on leave), we might have to fine-tune BERT ourselves.
Maybe we can reach out to the original authors and get a better version,

**Comment by asgerius** [comment]
git fukd
