### ISSUE TITLE
Make plots of performance improvement using multi-GPU for our daLKE code section

### ISSUE THREAD

**Issue by sorenmulli** [peleiden/daLUKE#60]

**Comment by asgerius** [comment]
GIver måske ikke så meget mening med plots, hvis Bernd aldrig giver mere end to gpuer? Men vi kan selvfølgeligt godt prøve at få fat i fire V100'er bare længe nok til at lave plots

**Comment by sorenmulli** [comment]
Behøver kun være en super-quickie til lige at have lidt pral ;)

**Comment by asgerius** [comment]
See branch feature/timeplot

I will probably not merge this in, as it is very hardcoded and not a proper part of DaLUKE
