### ISSUE TITLE
Decide what experiments and what analysis of pretraining model should be finished for report

### ISSUE THREAD

**Issue by sorenmulli** [peleiden/daLUKE#63]
@asgerius, ideas?

**Comment by asgerius** [comment]
Many

**Comment by asgerius** [comment]
Tanker:
- Datasætsannotering
- Lidt gittersøgning. Vi skal overveje, om vi kan bruge eksisterende, eller om der skal foretages en mere opdateret og systematisk søgning - jeg holder mest på førstnævnte. Ulempen ved det er, at vi aldrig endte med at bruge nogle af de undersøgte parametre.
- Vægtfix
- Entity vocab-beskæring
- Entity loss-vægtning
Så mangler vi i hvert fald ikke noget at skrive om

**Comment by sorenmulli** [comment]
Nej, det gør vi ikke - det der er også nogle big chungii. Kan være, vi skal bringe det op over for Larsus Kaius

> Datasætsannotering

Helt enig! En god praleboi og har også en væsentlig lærepointe

> Gittersøgning

Ja, det skal der nok være noget af

> Vægtfix

Ja, en smule - men kan også være meget nørdet 

> Enitty vocab beskæring

Også meget nørdet og kan vise mærkelige resultater, der er svære at sige noget til

> Entity loss-vægtning

Lets seee

**Comment by asgerius** [comment]
Entity attention?

**Comment by sorenmulli** [comment]
Yup! Den er nødvendig!

**Comment by asgerius** [comment]
Urgh, så skal der jo faktisk kodes vægtinitialisering til det :vomiting_face:

**Comment by sorenmulli** [comment]
Pænt meget konvergeret
