### ISSUE TITLE
Update plots

### ISSUE THREAD

**Issue by asgerius** [peleiden/daluke#84]
- [x] Don't plot epochs - this is only nice when there are less than ~20
- [x] Consider also doing running avg. on low k top k accuracies - depends on how it looks after doing above
- [ ] Maybe log scale x axis? Most interesting stuff happens relatively early, especially in big boi

**Comment by sorenmulli** [comment]
Pls use epochs for x axis

**Comment by asgerius** [comment]
I don't think so - everyone (e.g. LUKE and BERT) seems to use steps as their primary metric. It is also data-set size agnostic, so it gives a better impression on the amount of training IMO. An alternative could be to have both? https://stackoverflow.com/questions/10514315/how-to-add-a-second-x-axis-in-matplotlib

**Comment by sorenmulli** [comment]
But steps is not hyper parameter (batch size) agnostic either and thats even worse imo :S
And every time we have been looking at those plots we have been calculating the epochs in our heads :laughing:

**Comment by asgerius** [comment]
True, I guess - but the counter argument is that batch size varies much less than dataset size compared to BERT or LUKE. Maybe the best solution then is a double x axis? https://matplotlib.org/stable/gallery/subplots_axes_and_figures/secondary_axis.html
