### ISSUE TITLE
Error analysis on daLUKE

### ISSUE THREAD

**Issue by sorenmulli** [peleiden/daluke#87]

**Comment by asgerius** [comment]
Et par observationer fra forvirringsmatricen:
- Recallproblemerne er især MISC
- Der bliver ofte forudsagt LOC på ORG, hvilket giver mening, da mange organisationer indeholder steder i deres navn. Det modsatte sker dog ikke, men det skyldes nok, at stednavne ofte er en del af organisationsnavne, men ikke omvendt

Preds henad, annoteringer nedad
![image](https://user-images.githubusercontent.com/44878204/121811593-1cb02080-cc65-11eb-9b4a-89b03b2f37e6.png)

**Comment by sorenmulli** [comment]
Resolved in 706d4bca545e179e3fe2f2c459e5eec86c05cddd
