### ISSUE TITLE
Download and store both pretrained and NER models

### ISSUE THREAD

**Issue by sorenmulli** [peleiden/daluke#94]

**Comment by sorenmulli** [comment]
See dis, @asgerius 

https://github.com/alexandrainst/danlp/blob/master/danlp/download.py
https://github.com/alexandrainst/danlp/blob/master/danlp/download.py
https://github.com/alexandrainst/danlp/blob/master/danlp/download.py

**Comment by asgerius** [comment]
Nextcloud goes brrr
